# Generated by Django 4.0.4 on 2022-04-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philosophers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Philosophers',
            new_name='Philosopher',
        ),
    ]
